version: '3'

services:
  openorb:
    container_name: openorb
    build: "./app"
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data/
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  cron:
    container_name: cron
    build: "./cron"
    depends_on:
      - openorb
